# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifegame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifegame.World')),
            ],
        ),
    ]
