# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifegame', '0002_plot'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='alias',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
