# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-07 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifegame', '0004_plot_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
