# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 04:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifegame', '0006_auto_20190111_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='food_distribution',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='world',
            name='life_distribution',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
