# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lifegame', '0007_auto_20190111_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeform',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_father', to='lifegame.LifeForm'),
        ),
        migrations.AlterField(
            model_name='lifeform',
            name='mother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_mother', to='lifegame.LifeForm'),
        ),
    ]
